default_language_version:
    python: python3.12
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
        args: ['--autofix']
    -   id: check-ast
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: requirements-txt-fixer
    -   id: no-commit-to-branch
        args: [ '--branch', 'main' ]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.10
  hooks:
    - id: ruff-check
      args: [--fix]
    - id: ruff-format
