_mimetypes:
    JPG: &JPG image/jpeg
    PNG: &PNG image/png
    GIF: &GIF image/gif
    WEBP: &WEBP image/webp
    PDF: &PDF application/pdf
    MP3: &MP3 audio/mpeg
    WAV: &WAV audio/wav
    FLAC: &FLAC audio/flac
    M4A: &M4A audio/mp4
    MP4: &MP4 video/mp4
    QUICKTIME: &QUICKTIME video/quicktime
    WEBM: &WEBM video/webm

# OpenAI Models
gpt-5:
  knowledge_cutoff: 2024-10-01
  context_window: 400000
  max_output_tokens: 128000
  unsupported_parameters:
    - temperature
    - frequency_penalty
    - presence_penalty
    - repetition_penalty
    - top_k
  supports_streaming: true
  supports_structured_output: true
  supports_json: true
  supports_tools: true
  supports_logit_biasing: true
  accepts_files:
    - *JPG
    - *PNG
    - *GIF
    - *PDF
  cost_per_1m_input_tokens: 1.25
  cost_per_1m_cache_tokens: 0.125
  cost_per_1m_output_tokens: 10.0

gpt-5-mini:
  knowledge_cutoff: 2024-05-31
  context_window: 400000
  max_output_tokens: 128000
  unsupported_parameters:
    - temperature
    - frequency_penalty
    - presence_penalty
    - repetition_penalty
    - top_k
  supports_streaming: true
  supports_structured_output: true
  supports_json: true
  supports_tools: true
  supports_logit_biasing: true
  accepts_files:
    - *JPG
    - *PNG
    - *GIF
    - *PDF
  cost_per_1m_input_tokens: 0.25
  cost_per_1m_cache_tokens: 0.025
  cost_per_1m_output_tokens: 2.0

gpt-5-nano:
  knowledge_cutoff: 2024-05-31
  context_window: 400000
  max_output_tokens: 128000
  unsupported_parameters:
    - temperature
    - frequency_penalty
    - presence_penalty
    - repetition_penalty
    - top_k
  supports_streaming: true
  supports_structured_output: true
  supports_json: true
  supports_tools: true
  supports_logit_biasing: true
  accepts_files:
    - *JPG
    - *PNG
    - *GIF
    - *PDF
  cost_per_1m_input_tokens: 0.05
  cost_per_1m_cache_tokens: 0.005
  cost_per_1m_output_tokens: 0.4

gpt-4.1:
  tokenizer: tiktoken
  knowledge_cutoff: 2024-06-01
  context_window: 1047576
  max_output_tokens: 32768
  unsupported_parameters:
    - repetition_penalty
    - top_k
  supports_streaming: true
  supports_structured_output: true
  supports_json: true
  supports_tools: true
  supports_logit_biasing: true
  accepts_files:
    - *JPG
    - *PNG
    - *GIF
    - *PDF
  cost_per_1m_input_tokens: 2.0
  cost_per_1m_cache_tokens: 0.75
  cost_per_1m_output_tokens: 8.0

gpt-4.1-mini:
  tokenizer: tiktoken
  knowledge_cutoff: 2024-06-01
  context_window: 1047576
  max_output_tokens: 32768
  unsupported_parameters:
    - repetition_penalty
    - top_k
  supports_streaming: true
  supports_structured_output: true
  supports_json: true
  supports_tools: true
  supports_logit_biasing: true
  accepts_files:
    - *JPG
    - *PNG
    - *GIF
    - *PDF
  cost_per_1m_input_tokens: 0.1
  cost_per_1m_cache_tokens: 0.2
  cost_per_1m_output_tokens: 0.4

gpt-4.1-nano:
  tokenizer: tiktoken
  knowledge_cutoff: 2024-06-01
  context_window: 1047576
  max_output_tokens: 32768
  unsupported_parameters:
    - repetition_penalty
    - top_k
  supports_streaming: true
  supports_structured_output: true
  supports_json: true
  supports_tools: true
  supports_logit_biasing: true
  accepts_files:
    - *JPG
    - *PNG
    - *GIF
    - *PDF
  cost_per_1m_input_tokens: 0.1
  cost_per_1m_cache_tokens: 0.025
  cost_per_1m_output_tokens: 0.4

gpt-4o:
  tokenizer: tiktoken
  knowledge_cutoff: 2023-10-01
  context_window: 128000
  max_output_tokens: 16384
  unsupported_parameters:
    - repetition_penalty
    - top_k
  supports_streaming: true
  supports_structured_output: true
  supports_json: true
  supports_tools: true
  supports_logit_biasing: true
  accepts_files:
    - *JPG
    - *PNG
    - *GIF
    - *PDF
  cost_per_1m_input_tokens: 2.5
  cost_per_1m_cache_tokens: 1.25
  cost_per_1m_output_tokens: 10.0

gpt-4o-mini:
  tokenizer: tiktoken
  knowledge_cutoff: 2023-10-01
  context_window: 128000
  max_output_tokens: 16384
  unsupported_parameters:
    - repetition_penalty
    - top_k
  supports_streaming: true
  supports_structured_output: true
  supports_json: true
  supports_tools: true
  supports_logit_biasing: true
  accepts_files:
    - *JPG
    - *PNG
    - *GIF
    - *PDF
  cost_per_1m_input_tokens: 0.15
  cost_per_1m_cache_tokens: 0.075
  cost_per_1m_output_tokens: 0.6

# Anthropic Models
claude-opus-4-1:
  knowledge_cutoff: 2025-03-01
  context_window: 200000
  max_output_tokens: 32000
  unsupported_parameters:
    - variants
    - seed
    - frequency_penalty
    - presence_penalty
    - repetition_penalty
    - prediction
  supports_streaming: true
  supports_structured_output: true
  supports_json: true
  supports_tools: true
  supports_logit_biasing: false
  accepts_files:
    - *JPG
    - *PNG
    - *GIF
    - *WEBP
    - *PDF
  cost_per_1m_input_tokens: 15.0
  cost_per_1m_cache_tokens: 18.75
  cost_per_1m_output_tokens: 75.0

claude-opus-4-0:
  knowledge_cutoff: 2025-03-01
  context_window: 200000
  max_output_tokens: 32000
  unsupported_parameters:
    - variants
    - seed
    - frequency_penalty
    - presence_penalty
    - repetition_penalty
    - prediction
  supports_streaming: true
  supports_structured_output: true
  supports_json: true
  supports_tools: true
  supports_logit_biasing: false
  accepts_files:
    - *JPG
    - *PNG
    - *GIF
    - *WEBP
    - *PDF
  cost_per_1m_input_tokens: 15.0
  cost_per_1m_cache_tokens: 18.75
  cost_per_1m_output_tokens: 75.0

claude-sonnet-4-0:
  knowledge_cutoff: 2025-03-01
  context_window: 200000
  max_output_tokens: 64000
  unsupported_parameters:
    - variants
    - seed
    - frequency_penalty
    - presence_penalty
    - repetition_penalty
    - prediction
  supports_streaming: true
  supports_structured_output: true
  supports_json: true
  supports_tools: true
  supports_logit_biasing: false
  accepts_files:
    - *JPG
    - *PNG
    - *GIF
    - *WEBP
    - *PDF
  cost_per_1m_input_tokens: 3.0
  cost_per_1m_cache_tokens: 3.75
  cost_per_1m_output_tokens: 15.0

claude-3-7-sonnet-latest:
  knowledge_cutoff: 2024-11-01
  context_window: 200000
  max_output_tokens: 64000
  unsupported_parameters:
    - variants
    - seed
    - frequency_penalty
    - presence_penalty
    - repetition_penalty
    - prediction
  supports_streaming: true
  supports_structured_output: true
  supports_json: true
  supports_tools: true
  supports_logit_biasing: false
  accepts_files:
    - *JPG
    - *PNG
    - *GIF
    - *WEBP
    - *PDF
  cost_per_1m_input_tokens: 3.0
  cost_per_1m_cache_tokens: 3.75
  cost_per_1m_output_tokens: 15.0

claude-3-5-haiku-latest:
  knowledge_cutoff: 2024-07-01
  context_window: 200000
  max_output_tokens: 8192
  unsupported_parameters:
    - variants
    - seed
    - frequency_penalty
    - presence_penalty
    - repetition_penalty
    - prediction
  supports_streaming: true
  supports_structured_output: true
  supports_json: true
  supports_tools: true
  supports_logit_biasing: false
  accepts_files:
    - *JPG
    - *PNG
    - *GIF
    - *WEBP
    - *PDF
  cost_per_1m_input_tokens: 0.8
  cost_per_1m_cache_tokens: 1.0
  cost_per_1m_output_tokens: 4.0

claude-3-haiku-20240307:
  knowledge_cutoff: 2023-08-01
  context_window: 200000
  max_output_tokens: 4096
  unsupported_parameters:
    - variants
    - seed
    - frequency_penalty
    - presence_penalty
    - repetition_penalty
    - prediction
  supports_streaming: true
  supports_structured_output: true
  supports_json: true
  supports_tools: true
  supports_logit_biasing: false
  accepts_files:
    - *JPG
    - *PNG
    - *GIF
    - *WEBP
    - *PDF
  cost_per_1m_input_tokens: 0.25
  cost_per_1m_cache_tokens: 0.3
  cost_per_1m_output_tokens: 1.25

# Google Models
gemini-2.5-pro:
  knowledge_cutoff: 2025-01-01
  context_window: 1048576
  max_output_tokens: 65536
  unsupported_parameters:
    - repetition_penalty
    - prediction
  supports_streaming: true
  supports_structured_output: true
  supports_json: true
  supports_tools: true
  supports_logit_biasing: false
  accepts_files:
    - *JPG
    - *PNG
    - *PDF
    - *MP3
    - *WAV
    - *M4A
    - *MP4
    - *QUICKTIME
    - *WEBM
  cost_per_1m_input_tokens: 1.25
  cost_per_1m_cache_tokens: 1.25
  cost_per_1m_output_tokens: 10.0

gemini-2.5-flash:
  knowledge_cutoff: 2025-01-01
  context_window: 1048576
  max_output_tokens: 65536
  unsupported_parameters:
    - repetition_penalty
    - prediction
  supports_streaming: true
  supports_structured_output: true
  supports_json: true
  supports_tools: true
  supports_logit_biasing: false
  accepts_files:
    - *JPG
    - *PNG
    - *PDF
    - *MP3
    - *WAV
    - *M4A
    - *MP4
    - *QUICKTIME
    - *WEBM
  cost_per_1m_input_tokens: 0.3
  cost_per_1m_cache_tokens: 0.075
  cost_per_1m_output_tokens: 2.5

gemini-2.5-flash-lite:
  knowledge_cutoff: 2025-01-01
  context_window: 1048576
  max_output_tokens: 65536
  unsupported_parameters:
    - repetition_penalty
    - prediction
  supports_streaming: true
  supports_structured_output: true
  supports_json: true
  supports_tools: true
  supports_logit_biasing: false
  accepts_files:
    - *JPG
    - *PNG
    - *PDF
    - *MP3
    - *WAV
    - *M4A
    - *MP4
    - *QUICKTIME
    - *WEBM
  cost_per_1m_input_tokens: 0.1
  cost_per_1m_cache_tokens: 0.025
  cost_per_1m_output_tokens: 0.4

gemini-2.0-flash:
  knowledge_cutoff: 2024-08-01
  context_window: 1048576
  max_output_tokens: 8192
  unsupported_parameters:
    - repetition_penalty
    - prediction
  supports_streaming: true
  supports_structured_output: true
  supports_json: true
  supports_tools: true
  supports_logit_biasing: false
  accepts_files:
    - *JPG
    - *PNG
    - *PDF
    - *MP3
    - *WAV
    - *M4A
    - *MP4
    - *QUICKTIME
    - *WEBM
  cost_per_1m_input_tokens: 0.1
  cost_per_1m_cache_tokens: 0.025
  cost_per_1m_output_tokens: 0.4

gemini-2.0-flash-lite:
  knowledge_cutoff: 2024-08-01
  context_window: 1048576
  max_output_tokens: 8192
  unsupported_parameters:
    - repetition_penalty
    - prediction
  supports_streaming: true
  supports_structured_output: true
  supports_json: true
  supports_tools: true
  supports_logit_biasing: false
  accepts_files:
    - *JPG
    - *PNG
    - *PDF
    - *MP3
    - *WAV
    - *M4A
    - *MP4
    - *QUICKTIME
    - *WEBM
  cost_per_1m_input_tokens: 0.075
  cost_per_1m_output_tokens: 0.3

# DeepInfra Models
meta-llama/Meta-Llama-3.1-70B-Instruct:
  tokenizer: hf
  knowledge_cutoff: 2023-12-01
  context_window: 128000
  max_output_tokens: 2048
  unsupported_parameters:
    - top_k
    - prediction
  supports_streaming: true
  supports_structured_output: false
  supports_json: true
  supports_tools: true
  supports_logit_biasing: true
  accepts_files: []
  cost_per_1m_input_tokens: 0.23
  cost_per_1m_output_tokens: 0.4

meta-llama/Meta-Llama-3.1-8B-Instruct:
  tokenizer: hf
  knowledge_cutoff: 2023-12-01
  context_window: 128000
  max_output_tokens: 2048
  unsupported_parameters:
    - top_k
    - prediction
  supports_streaming: true
  supports_structured_output: false
  supports_json: true
  supports_tools: true
  supports_logit_biasing: false
  accepts_files: []
  cost_per_1m_input_tokens: 0.03
  cost_per_1m_output_tokens: 0.05
